name: First Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
            echo "Hello World"
            echo "Hey I am talking to you"
      - name: Print goodby
        run: echo "Done - bye!"
